@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

skinparam linetype ortho

Title CollaboCraft - System Context Diagram

Person(client, "Клиент", "Пользователь системы: создатель, редактор, наблюдатель")

System(collabocraft, "CollaboCraft", "Система совместного редактирования документов")

System_Ext(minio, "MinIO", "Система хранения изображений и медиафайлов")
System_Ext(smtp, "SMTP-сервер", "Система отправки email-уведомлений")

Rel(client, collabocraft, "Использует")
Rel(collabocraft, minio, "Сохраняет/загружает файлы")
Rel(collabocraft, smtp, "Отправляет уведомления")

@enduml